source 'https://git.ms.netease.com/neteaselottery/ldcpspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.ms.netease.com/commonlibraryios/podspec.git'
source 'https://git.ms.netease.com/PettyLoan/ldplspecs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test
pod 'LDKit', '~> 0.2.5'
pod 'LDRoutes', '0.0.1'
pod 'LDPopupController', '~> 0.1.5'
#pod 'LDKWUserCenter', '~> 0.1.1'
pod 'LDKWUserCenter', :git=>'https://git.ms.netease.com/PettyLoan/LDKWUserCenter.git',:branch=>'master'
pod 'LDKWNetworking', '~> 0.1.0'
pod 'LDKWWebViewController', '~> 0.1.1'

#第三方库
pod 'Masonry', '~> 1.1.0'
pod 'YYModel', '~> 1.0.4'
pod 'SDWebImage', '~> 4.1.0'
pod 'Reachability', '~> 3.2'
pod 'SVProgressHUD', '~> 2.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'MKAdditions', '~> 0.1.4'
pod 'TTTAttributedLabel', '1.13.4'
pod 'KMNavigationBarTransition', '~> 1.1.1'
pod 'KMCGeigerCounter', '~>0.2.0'

  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
